# Generated by Django 5.1 on 2024-08-21 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_previews/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_previews', to='Overview.post')),
            ],
        ),
    ]
