# Generated by Django 5.1 on 2024-08-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0002_postpreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostPreview',
            new_name='Post_preview',
        ),
    ]
