# Generated by Django 5.1 on 2024-08-24 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0003_rename_postpreview_post_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('work', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='user_avatars/')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='author_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='Overview.users'),
        ),
    ]
