# Generated by Django 5.1 on 2024-08-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0004_users_alter_post_author_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
