# Generated by Django 5.1 on 2024-08-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0005_rename_users_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='work',
            new_name='job',
        ),
    ]
