# Generated by Django 5.1 on 2024-08-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0006_rename_work_user_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=50, unique=True)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='styles/previews/')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='post_preview',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_name',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Overview.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_thumbnail',
            field=models.ImageField(default=0, upload_to='posts/thumbnails/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_thumbnail',
            field=models.ImageField(default=0, upload_to='users/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='users/avatars/'),
        ),
        migrations.AddField(
            model_name='post',
            name='style',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Overview.style'),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Overview.type'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post_preview',
        ),
    ]
