# Generated by Django 5.1 on 2024-08-25 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Overview', '0007_style_type_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Overview.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_thumbnail',
            field=models.ImageField(upload_to='posts/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Overview.style'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Overview.type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_thumbnail',
            field=models.ImageField(upload_to='users/thumbnails/'),
        ),
    ]
